Update ms-s7-web-uninstaller

diff --git a/ms-s7-web-uninstaller b/ms-s7-web-uninstaller
--- a/ms-s7-web-uninstaller
+++ b/ms-s7-web-uninstaller
@@ -1,1 +1,61 @@
+    IW   ms-s7-web-uninstaller (Modified)                                                                                                                                                                 Row 39   Col 40   9:12  Ctrl-K H for help
+#!/usr/bin/env bash
+#
+# The MIT License (MIT)
+#
+# ms-s7-web-installer - installer for ms-s7-web
+#
+# Copyright (c) 2016 Kari Karvonen
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the "Software"), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice shall be included in all
+# copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 
+echo "$0 Welcome to MS-S7-WEB ant_switch extension uninstaller"
+echo ""
+echo "$0 Do you want to uninstall KiwiSDR antenna switch extension (y/n)"
+read ok
+if [ "x$ok" == "xy" ]; then
+        echo ""
+        echo "$0 Removing files"
+        # remove config
+        rm /etc/default/ms-s7-web
+        # remove executable
+        rm /usr/local/bin/ms-s7-web
+        # Remove extension files
+        rm -rf /root/Beagle_SDR_GPS/extensions/ant_switch
+        rm -rf /root/Beagle_SDR_GPS/web/extensions/ant_switch
+        echo ""
+        echo "$0 Rebuilding KiwiSDR. This will take about 13 minutes."
+        echo ""
+        cd /root/Beagle_SDR_GPS
+        make clean
+        make
+        make install
+        echo ""
+        echo "$0 Compile finished. Restart needed. Do you want to restart KiwiSDR now (y/n)?"
+        read ok
+        if [ "x$ok" == "xy" ]; then
+                echo "$0 Restarting KiwiSDR"
+                make stop
+                make start
+        else
+                echo "$0 Not restarting."
+        fi
+else
+        echo "$0 Uninstall aborted."
+        exit 1
+fi
