Dont switch antenna if default antenna is already selcted

diff --git a/scripts/reset-to-default-antennas-when-no-users-online b/scripts/reset-to-default-antennas-when-no-users-online
--- a/scripts/reset-to-default-antennas-when-no-users-online
+++ b/scripts/reset-to-default-antennas-when-no-users-online
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # The MIT License (MIT)
-#
-# reset-to-default-antennas-when-no-users-online
+#	
+# reset-to-default-antennas-when-no-users-online 
 #
 # Copyright (c) 2017 Kari Karvonen
 #
@@ -24,7 +24,7 @@
 # SOFTWARE.
 
 # Specify default antennas. This can be single antenna on comma separated
-# list many antennas
+# list many antennas 
 # DEFAULT_ANTENNAS=1,2,7
 DEFAULT_ANTENNAS=2
 
@@ -50,8 +50,8 @@ ANTSWITCHEXEC=/root/extensions/ant_switch/frontend/ant-switch-frontend
 ADMINJSON=/root/kiwi.config/admin.json
 
 if ! [[ -x "$ANTSWITCHEXEC" ]]; then
-        echo "$0: Antenna switch script $ANTSWITCHEXEC not found or it is not executable. Exit."
-        exit 1
+	echo "$0: Antenna switch script $ANTSWITCHEXEC not found or it is not executable. Exit."
+	exit 1
 fi
 
 if ! [[ -r "$ADMINJSON" ]]; then
@@ -64,22 +64,25 @@ STATUSURL="http://127.0.0.1:$PORT/status"
 
 STATUS=`$CURLEXEC $STATUSURL $CURLOPTS`
 if [ "x$STATUS" == "x" ]; then
-        echo "$0: Status url $STATUSURL could not be retriewed. Exit."
-        exit 1
+	echo "$0: Status url $STATUSURL could not be retriewed. Exit."
+	exit 1
 fi
 
 ONLINEUSERS=`echo $STATUS | sed -e "s/.* users=\([0-9]\) .*/\1/"`
 re='^[0-9]+$'
 if ! [[ $ONLINEUSERS =~ $re ]] ; then
-        echo "$0: Cannot parse users number from $STATUSURL. Exit."
-        exit 1
+	echo "$0: Cannot parse users number from $STATUSURL. Exit."
+	exit 1
 fi
 
 if [ "$ONLINEUSERS" == "0" ]; then
-        # No users online, switch to default antennas
-        ANTENNAS=`echo $DEFAULT_ANTENNAS | tr ',' ' '`
-        $ANTSWITCHEXEC g
-        for antenna in $ANTENNAS; do
-                $ANTSWITCHEXEC +$antenna
-        done
+	# No users online, switch to default antennas
+	selected=`$ANTSWITCHEXEC s | sed -e 's/^Selected antennas: //'`
+	if [ "$selected" != "$DEFAULT_ANTENNAS" ]; then
+		ANTENNAS=`echo $DEFAULT_ANTENNAS | tr ',' ' '`
+		$ANTSWITCHEXEC g
+		for antenna in $ANTENNAS; do
+			$ANTSWITCHEXEC +$antenna
+		done
+	fi
 fi
